apiVersion: v1
kind: ReplicationController
metadata:
  name: restfs-contr
  labels:
    app: thesis
    role: backend
    tier: filesistem
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thesis
        role: backend
        tier: filesistem
    spec:
      containers:
      - name: thesis-rest-filesistem
        image: djob195/thesis-rest-filesistem
        volumeMounts:
        - name: upload-filesistem
          mountPath: /usr/src/app/uploads
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8080"
        - name: DBTYPE
          value: "mongodb"
        - name: USERDB
          value: "est1010114"
        - name: PASSWORDDB
          value: "20403232d"
        - name: PATHDB
          value: "ds133192.mlab.com"
        - name: PORTDB
          value: "33192"
        - name: NAMEDB
          value: "thesis2"
        - name: CADUCIDAD_TOKEN
          value: "2592000"
        - name: SEED
          value: "3st3-es-3l-Se3D-De-Pr0ducci0n"
        - name: ADMINUSER
          value: "djob195@gmail.com"
        - name: ADMINPASSWORD
          value: "123456"
        - name: DESDE
          value: "0"
        - name: LIMITE
          value: "5"
        ports:
        - containerPort: 8080
      volumes:
      - name: upload-filesistem
        emptyDir: {}